### ISSUE TITLE
how set system-username

### ISSUE THREAD

**Issue by badlee** [Roave/shorty#7]
I worte a SMPP application with nodejs and shorty,

I try to connect to an carrier, but i can't set system-username,
How make it?...

With kannel the config is :

```
group=smsc
smsc=smpp
smsc-id=azur8800
interface-version=34
host=xxx.xxx.xxx.xxx
port=2775
transceiver-mode = 1
system-id=samtosa
smsc-username=oshimin
smsc-password=XXXXXXX
system-type=default
```

My config with shorty is :

``` javascript
{
    "smpp": [
        {
            "mode":         "transceiver",
            "host":         "xxx.xxx.xxx.xxx",
            "port":         2775,
            "system_id":    "oshimin",
            "password":     "XXXXXXX",
            "interface_version" : 34,
            "system_type":  "default",
            "addr_ton":     0,
            "addr_npi":     1,
            "addr_range":   "",
            "timeout":      30,
            "client_keepalive":  false,
            "client_reconnect_interval": 2000,
            "strict":       1
        }
    ],
    "debug":    true,
}
```

For kannel all is ok but for shorty i can't connect to the carrier, please help me.

**Comment by bjyoungblood** [comment]
There is no username field defined in SMPP 3.4, issue 1.2. According to the protocol specification, system_id "dentifies the ESME system requesting to bind... with the SMSC." In my experience, carriers typically use system_id instead of username.

If your carrier requires username, you can modify the PDU definitions in [./lib/smpp-definitions.js](https://github.com/mtd/shorty/blob/master/lib/smpp-definitions.js#L166).

**Comment by badlee** [comment]
Thank you for your reply, I have to settle the problem with my carrier and he made this optional field.

Best regards.
